-- Query to back up Database

BACKUP DATABASE TF_TRANSLATIONS TO DISK = N'PATH\FILE.BAK'
WITH NOFORMAT, INIT, NAME = N'DB1' , SKIP, NOREWIND, NOUNLOAD, STATS = 10

BACKUP DATABASE TFDB_VIORYL TO DISK = N'PATH\FILE.BAK'
WITH NOFORMAT, INIT, NAME = N'DB2' , SKIP, NOREWIND, NOUNLOAD, STATS = 10

GO

-- Script 4 function

DECLARE @P4th varchar(80)
DECLARE @DB nvarchar(20)

SELECT @P4th = (SELECT 'PATH\FILE.' + 
convert(varchar(80),GetDate(),102) + '.bak') 
SET @DB='FILE'

BACKUP DATABASE @DB TO DISK=@P4th
GO
